version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
    timezone: America/Los_Angeles
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: flake8
    versions:
    - "> 3.8.1, < 3.9"
  - dependency-name: pytest
    versions:
    - "> 5.4.2, < 5.5"
  - dependency-name: python-lambda
    versions:
    - ">= 11.7.a, < 11.8"
