region: us-east-1

function_name: semantic_query_service
handler: service.handler
role: lambda_api
description: AWS Lambda mapping a search query into controlled vocabulary filters and a fulltext query using ITA Taxonomy API

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.
#aws_access_key_id: 
#aws_secret_access_key: 

# dist_directory: dist
timeout: 300
# memory_size: 512
