region: us-east-1

function_name: semantic_query_service
handler: service.handler
role: lambda_api
runtime: python3.8
description: Map a search query into controlled vocabulary filters and a fulltext query using ITA Taxonomy API
environment_variables:
  TAXONOMIES_API_KEY: ${TAXONOMIES_API_KEY}

# if access key and secret are left blank, boto will use the credentials
# defined in the [default] section of ~/.aws/credentials.

timeout: 300
memory_size: 128
